-----RAILWAY MANAGEMENT SYSTEM TABLES------------------------

-- STATIONS TABLE

CREATE TABLE STATIONS(STATION_ID NUMBER PRIMARY KEY,
                      STATION_NAME VARCHAR2(200));
					  

-- TRAINS TABLE

CREATE TABLE TRAINS(TRAIN_ID NUMBER PRIMARY KEY,
                    TRAIN_NAME VARCHAR2(100),
                    SOURCE_STATION_ID NUMBER REFERENCES STATIONS(STATION_ID),
                    DEST_STATION_ID NUMBER REFERENCES STATIONS(STATION_ID));
					

------ TRAINS SCHEDULE

CREATE TABLE TRAIN_SCH(SCH_ID NUMBER PRIMARY KEY,
                       TRAIN_ID NUMBER REFERENCES TRAINS(TRAIN_ID),
                       STATION_ID NUMBER REFERENCES STATIONS(STATION_ID),
                       ARRIVAL_TIME TIMESTAMP,
                       DEPARTURE_TIME TIMESTAMP);
					   

------ PASSANGERS TABLE

CREATE TABLE PASSENGERS(PASSENGER_ID NUMBER PRIMARY KEY,
                        PASSANGER_NAME VARCHAR2(100) NOT NULL,
                        AGE NUMBER,
                        GENDER VARCHAR2(10));
						
						
----- BOOKINGS TABLE

CREATE TABLE BOOKINGS(BOOKING_ID NUMBER PRIMARY KEY,
                      PASSENGER_ID NUMBER REFERENCES PASSENGERS(PASSENGER_ID),
                      TRAIN_ID NUMBER REFERENCES TRAINS(TRAIN_ID),
                      BOOKING_DATE DATE DEFAULT SYSDATE,
                      SEAT_NUMBER NUMBER,
                      STATUS VARCHAR2(50));
					  
---- WAITLIST TABLE 

CREATE TABLE WAITLIST(WAITLIST_ID NUMBER PRIMARY KEY,
                      PASSENGER_ID NUMBER REFERENCES PASSENGERS(PASSENGER_ID),
                      TRAIN_ID NUMBER REFERENCES TRAINS(TRAIN_ID),
                      REQUEST_DATE DATE DEFAULT SYSDATE,
                      WAITLIST_POSITION NUMBER);
                      
                      
                