---- RAILWAY MANAGEMENT TRIGGER TO EXPIRE BOOKING


CREATE OR REPLACE TRIGGER BOOKING_EXPIRY_TRIGGER
AFTER INSERT OR UPDATE ON TRAIN_SCH
DECLARE
BEGIN
 
 UPDATE BOOKINGS
 SET status = 'EXPIRED'
 WHERE train_id IN (SELECT TRAIN_ID FROM train_sch WHERE train_sch.departure_time < SYSDATE)
 AND  status = 'BOOKED';
 
 END;