--------------RAILWAY MANAGEMENT SYSTEM SEQUENCE FOR AUTOGENRATING

-- BOOKINGS SEQUENCE

CREATE SEQUENCE BOOKING_SEQ START WITH 1 INCREMENT BY 1;
    
-- WAITLIST_SEQ
	
CREATE SEQUENCE WAITLIST_SEQ START WITH 1 INCREMENT BY 1;